# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_title', models.CharField(max_length=50, verbose_name='T_TITLE')),
                ('t_content', models.TextField(verbose_name='T_CONTENT')),
                ('t_modify_date', models.DateTimeField(auto_now=True, verbose_name='T_Modify Date')),
            ],
            options={
                'ordering': ('-t_modify_date',),
                'db_table': 'tutorial_posts',
                'verbose_name': 't_post',
                'verbose_name_plural': 't_posts',
            },
        ),
    ]
