# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpost',
            options={'ordering': ('-modify_date',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RemoveField(
            model_name='tpost',
            name='t_content',
        ),
        migrations.RemoveField(
            model_name='tpost',
            name='t_modify_date',
        ),
        migrations.RemoveField(
            model_name='tpost',
            name='t_title',
        ),
        migrations.AddField(
            model_name='tpost',
            name='content',
            field=models.TextField(default='SOME STRING', verbose_name='CONTENT'),
        ),
        migrations.AddField(
            model_name='tpost',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify Date'),
        ),
        migrations.AddField(
            model_name='tpost',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=50, verbose_name='TITLE'),
        ),
    ]
