# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20161129_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpost',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='SOME STRING', help_text='one word for title alias.', unique=True, verbose_name='SLUG'),
        ),
    ]
